=== Madsmal/iCook/src/application/RecipeLibrary/rezepte.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT recipe (title,ID,startdate?,changedate?,target,ingredients+,preparation+,
variation*,remark*,technique*,sidedish*,privateremark*,duration*,source*,
regionoforigin*)>
<!ELEMENT title (#PCDATA|quote)*>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT startdate (#PCDATA)>
<!ELEMENT changedate (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT ingredients (ingredient*)>
<!ATTLIST ingredients part CDATA #IMPLIED>
<!ELEMENT ingredient (quantity,unit,iname)>
<!ELEMENT tasks (task*)>
<!ATTLIST tasks part CDATA #IMPLIED>
<!ELEMENT task(ID, prereq, time, attentionRequired, taskString)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT prereq (#PCDATA |pagereference|quote|emph|bold|typewriter|italics )*>
<!ELEMENT time (#PCDATA)>
<!ELEMENT attentionRequired (#PCDATA)>
<!ELEMENT taskString (#PCDATA |pagereference|quote|emph|bold|typewriter|italics )*>
<!ELEMENT quantity  (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT iname   (#PCDATA |pagereference|quote|emph|bold|typewriter|italics )*>
<!ELEMENT preparation (#PCDATA|citation|underline|texspecial|pagereference|reference|quote|indexentry|emph|bold|typewriter|italics|namefont|sansserif)*>
<!ATTLIST preparation part CDATA #IMPLIED>
<!ELEMENT variation (#PCDATA|citation|underline|namefont|texspecial|quote|pagereference|indexentry|jumptarget|emph|bold|typewriter|italics|sansserif)*>
<!ELEMENT remark (#PCDATA |citation|texspecial|namefont|underline|indexentry|pagereference|quote|emph|bold|typewriter|italics|sansserif)*>
<!ELEMENT privateremark (#PCDATA|texspecial|underline|namefont|quote|indexentry|emph|bold|typewriter|italics|sansserif)*>
<!ELEMENT duration (durationspecial?,totaltime, worktime)>
<!ELEMENT totaltime (#PCDATA|emph|bold|typewriter|italics)*>
<!ELEMENT worktime (#PCDATA|emph|bold|typewriter|italics)*>
<!ELEMENT durationspecial (#PCDATA|emph|bold|typewriter|italics)*>
<!ELEMENT source (#PCDATA|citation|emph|typewriter|quote|indexentry)*>
<!ELEMENT technique (#PCDATA)>
<!ELEMENT sidedish (#PCDATA)>
<!ELEMENT regionoforigin (#PCDATA)>
<!ELEMENT frac (num,denom)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT denom (#PCDATA)>
<!ELEMENT range (from,to)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT refernce (#PCDATA)>
<!ELEMENT citation (#PCDATA)>
<!ELEMENT indexentry (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT pagereference (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT emph (#PCDATA)>
<!ELEMENT typewriter (#PCDATA)>
<!ELEMENT italics (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT sansserif (#PCDATA)>
<!ELEMENT namefont (#PCDATA)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT texspecial (#PCDATA)>
<!ELEMENT jumptarget (#PCDATA)>
<!ENTITY  deg "°">

=== Madsmal/iCook/src/application/RecipeLibrary/asciuta.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cookbook SYSTEM "rezepte.dtd">
<recipe>
<title>Nudeln mit Bologneser Sauce</title>
<ID>36</ID>
<startdate>01.01.1995</startdate>
<changedate>04.08.1997</changedate>
<target>
Für 4-6 Personen (für 6-10 als Vorspeise)
</target>
<ingredients>
<ingredient>
<quantity>1000</quantity>
<unit>g</unit>
<iname>Hackfleisch</iname>
</ingredient>
<ingredient>
<quantity>200</quantity>
<unit>g</unit>
<iname>durchwachsenen Speck</iname>
</ingredient>
<ingredient>
<quantity>2-3</quantity>
<unit></unit>
<iname>Zwiebeln</iname>
</ingredient>
<ingredient>
<quantity>2-3</quantity>
<unit></unit>
<iname>Knoblauchzehen</iname>
</ingredient>
<ingredient>
<quantity>1</quantity>
<unit></unit>
<iname>Dose Tomaten (850 ml)</iname>
</ingredient>
<ingredient>
<quantity>2</quantity>
<unit>EL</unit>
<iname>Tomatenmark</iname>
</ingredient>
<ingredient>
<quantity></quantity>
<unit></unit>
<iname>Salz, Pfeffer</iname>
</ingredient>
<ingredient>
<quantity></quantity>
<unit></unit>
<iname>Oregano</iname>
</ingredient>
<ingredient>
<quantity>500-750</quantity>
<unit>g</unit>
<iname>Nudeln, z.B. Spaghetti</iname>
</ingredient>
<ingredient>
<quantity>100</quantity>
<unit>g</unit>
<iname>Parmesan, frisch gerieben</iname>
</ingredient>

</ingredients>
<preparation>
Den Speck und die Zwiebeln fein würfeln 
und anbraten, aber nicht bräunen. Das 
Hackfleisch ebenfalls anbraten und dabei möglichst
fein zerteilen. Alles mit den Tomaten in einen Topf
geben und den Wein sowie die Gewürze hinzufügen. 
Mindestens 1 h, besser 2 h, sanft köcheln lassen
und dabei gelegentlich umrühren.
Die Sauce muß dicklich werden, aber nicht fest. 
Die Nudeln in 2-3 l Salzwasser circa 8-12 min kochen.
Entweder getrennt servieren oder die Sauce mit den
abgegossenen Nudeln mischen. Dazu den Parmesan reichen.
</preparation>
<variation>
Feingehackte Paprika und Möhren zugeben. 
</variation>
<remark>
Wenn kein Speck verwendet wird, sollte man möglichst 
Hackfleisch <quote>halb und halb</quote> oder reines Schweinehack
verwenden, weil das Gericht dann herzhafter und saftiger wird.
</remark>
<privateremark>
Am einfachsten ist es, den Speck und die Zwiebeln
durch die grobe (6 mm) Scheibe des Fleischwolfs der
BOSCH Küchenmaschine  zu drehen.
</privateremark>
<duration>
<totaltime>2:30</totaltime>
<worktime>1 h</worktime>

</duration>
<source>Herbert Fischer</source>
</recipe>
